### ISSUE TITLE
Provider 1.13.0: `tags` is not expected here

### ISSUE THREAD

**Issue by MatthiasWinzeler** [Azure/terraform-provider-azapi#462]
After upgrading to the latest provider version 1.13.0 I stumbled upon a new error:

```hcl
resource "azapi_resource" "routing_intent" {
  type      = "Microsoft.Network/virtualHubs/routingIntent@2023-09-01"
  name      = "${local.name_prefix}-routing-intent"
  parent_id = azurerm_virtual_hub.hub.id
  body = jsonencode({
    properties = {
      routingPolicies = [{
        name = "InternetTrafficPolicy"
        destinations = [
          "Internet"
        ]
        nextHop = azapi_resource.palo_nva.id
      }]
    }
  })
}
```

Fails with the following error message:

```
╷
│ Error: Invalid configuration
│
│   with azapi_resource.routing_intent,
│   on palo.tf line 154, in resource "azapi_resource" "routing_intent":
│  154: resource "azapi_resource" "routing_intent" {
│
│ embedded schema validation failed: the argument "body" is invalid:
│ `tags` is not expected here. Do you mean `etag`?
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
╵
```

It works fine with provider version 1.12.1.

**Comment by ms-henglu** [comment]
Hi @MatthiasWinzeler ,

Thank you for taking time to report this issue!

Is this `routing_intent` an existing resource? Or you're creating it?

**Comment by mgmm13** [comment]
also encountered the same issue with azapi regarding tags just now.

**Comment by wegmans-alex-beck** [comment]
We are running into a similar issue.

```
╷
│ Error: Invalid configuration
│ 
│   with module.storage_account.azapi_resource.storage_account_container,
│   on ../modules/storage_account/main.tf line 122, in resource "azapi_resource" "storage_account_container":
│  122: resource "azapi_resource" "storage_account_container" {
│ 
│ embedded schema validation failed: the argument "body" is invalid:
│ `tags` is not expected here. Do you mean `etag`? 
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
╵
```

**Comment by MatthiasWinzeler** [comment]
@ms-henglu no worries, we're in open source here, just trying to help out ;)

Setting `schema_validation_enabled = false` doesn't work, it looks like the `tags` field is sent to the backend which rejects it:

```
╷
│ Error: Failed to create/update resource
│
│   with azapi_resource.routing_intent[0],
│   on palo.tf line 154, in resource "azapi_resource" "routing_intent":
│  154: resource "azapi_resource" "routing_intent" {
│
│ creating/updating Resource: (ResourceId
│ "..."
│ / Api Version "2023-09-01"): PUT
│ https://management.azure.com/subscriptions/.../resourceGroups/...providers/Microsoft.Network/virtualHubs/.../routingIntent/..-routing-intent
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidRequestFormat
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidRequestFormat",
│     "message": "Cannot parse the request.",
│     "details": [
│       {
│         "code": "InvalidJson",
│         "message": "Could not find member 'tags' on object of type 'RoutingIntent'. Path 'tags', line 1, position 343."
│       }
│     ]
│   }
│ }
│ --------------------------------------------------------------------------------
│
```

**Comment by wegmans-alex-beck** [comment]
We have forced the version to v1.12.1 to workaround the issue.

```tf
terraform {
  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = "1.12.1"
    }
  }
}
````

**Comment by eOkadas** [comment]
Same issue here, using "schema_validation_enabled = false"  did not work. 
we pinned our provider to 1.12.1 

Good luck on the fix, will be watching for news 🙏

**Comment by ms-henglu** [comment]
Hi all,

The bug fix has been released in v1.13.1, would you please give it a try? Thanks!

**Comment by MatthiasWinzeler** [comment]
@ms-henglu works fine now, many thanks!

**Comment by sravyavattem** [comment]
facing the same issue with agape 1.14.1. changed versions to 1.13.1 and 1.12.1 and the error persisted.

<img width="1239" alt="image" src="https://github.com/Azure/terraform-provider-azapi/assets/50862179/f26ea558-11d6-44a4-879d-d7f5bcb7a36e">
