### ISSUE TITLE
Microsoft.Network/virtualHubs/routingIntent fails on release v1.13.0 - ChainedTokenCredential Authentication Failed, Identity not found

### ISSUE THREAD

**Issue by NikolaiKleppe** [Azure/terraform-provider-azapi#475]
Hi,

Today our pipeline for configuring routing intent on Virtual WAN fails with errors regarding identity. 
I see version v1.13.0 was released yesterday with changes to identity behaviour. 
Locking to the previous version v1.12.1 makes it work again.

Error:

![image](https://github.com/Azure/terraform-provider-azapi/assets/7556264/e7a6b9ec-58b4-47dd-87e6-3f0d687043db)

Code:

```hcl
resource "azapi_resource" "routing_intent" {
  type      = "Microsoft.Network/virtualHubs/routingIntent@2023-05-01"
  parent_id = data.azurerm_virtual_hub.vwan_hub.id
  name      = "vwan-hub-<redacted>_RoutingIntent" # Match name in portal

  body = jsonencode({
    properties = {
      routingPolicies = [ 
        {
          name         = "PublicTraffic",
          destinations = ["Internet"],
          nextHop      = azurerm_firewall.firewall.id
        },
        {
          name         = "PrivateTraffic"
          destinations = ["PrivateTraffic"]
          nextHop      = azurerm_firewall.firewall.id
        }
      ]
    }
  })
}
```

There is no identity configuration on either Virtual WAN or Virtual WAN Hubs so I'm unsure why this error occurs.
The firewall resource which this depends on is made with AzureRM, but no identity is configured there either.

**Comment by ms-henglu** [comment]
Hi @NikolaiKleppe ,

Thank you for taking time to report this issue!

I'll keep investigating why the behavior is different between 1.12.1 and 1.13.0. A way to mitigate this issue is using `use_msi = false` if you're not authenticating with Azure by managed identity. 

More details, please check: https://registry.terraform.io/providers/Azure/azapi/latest/docs#use_msi

**Comment by ms-henglu** [comment]
Hi @NikolaiKleppe , are you authenticating with Azure by client certificate?

**Comment by NikolaiKleppe** [comment]
Hi @ms-henglu, yes we are using certificate authentication (from app registration)

**Comment by ms-henglu** [comment]
Hi @NikolaiKleppe ,

The bug fix has been released in v1.13.1, would you please have a try? Thanks.

**Comment by NikolaiKleppe** [comment]
Hi @ms-henglu ,

It works now with v1.13.1  - Thanks a lot!

**Comment by sausagedogcoffee** [comment]
Have the same issue, v1.13.1  didn't resolve but `use_msi = false` did.
